### ISSUE TITLE
Support for SiFive HiFive1 Rev B (Freedom E310 SoC)

### ISSUE THREAD

**Issue by AntonHermann** [hex-five/multizone-iot-sdk#1]
Hey there :)
recently support for the *SiFive HiFive1 Rev B (Freedom E310 SoC)* has been added to [the multizone-sdk repo](https://github.com/hex-five/multizone-sdk).
I'm highly interested in using this particular board with the multizone-iot-sdk as well.

Are there currently any plans to add support for the HiFive board as well?

If not, could you estimate the amount of effort needed to make the IoT-SDK work with the HiFive board?

Thanks a lot in advance,  
kind regards,  
Anton

**Comment by cgarlati** [comment]
Anton:

We have no plans to port the MultiZone Secure IoT Firmware to this board.
The E310 limited ram (16KB) makes it unsuitable for TLS applications.

Cheers
Cesare

**Comment by AntonHermann** [comment]
Cheers Cesare,
first of all, thanks for the quick reply!

I have not worked much with the HiFive board. but as far as I understand the ESP32 on the board has a TCP/IP stack with SSL capabilities included. Couldn't this be used instead of using a software stack running on the RISC-V processor?

Best wishes,
Anton

**Comment by cgarlati** [comment]
Anton: This is really a question for SiFive. Cheers Cesare
