### ISSUE TITLE
Connecting an external button to an Arty A7

### ISSUE THREAD

**Issue by biertimpel** [hex-five/multizone-iot-sdk#3]
Hey :)

We want to connect an external button to an Arty A7 and develop a small IoT application.
We identified the following steps to be crucial for a successful connection:

1. Add the location of the irq to zone 4 in the multizone.cfg file. Through trial and error, we figured out that we can use any free number between 16 and 31 and chose '20'.
2. Initialize a GPIO pin in zone 4 similar to the buttons on the board. Essentially we copied the code and used a different number, as well as using 20 for the location of the irq.
3. Add the irq to the trap vector (trap_vec).

We tried to initialize every GPIO pin and link it to the irq as well as choosing a random pin on the board and connecting the button to GND and the respective pin. We hoped that it would work for 1 pin, which we could find by eliminating one pin at a time. This did not work, since the interrupt was not triggered, even if every entry in the GPIO array (GPIO_IN_EN) is enabled and (in theory) is linked to the irq of the button.

Maybe this is due to the overkill, but we did not find any resources on how the GPIO pins of the Arty A7 correlate with the different numbers in the MultiZone Firmware.

Is there any information on which pin to use and how to initialize the pin? Furthermore how do we properly link the irq to the pin?

Thanks a lot,
Jonny

**Comment by Hex-Five-Labs** [comment]
@biertimpel Jonny:

Take a look at the X300 [GPIO interrupt table](https://github.com/hex-five/multizone-fpga/tree/master#appendix---gpio-interrupts-table) and to the branch [GPIO interrupt examples](https://github.com/hex-five/multizone-sdk/tree/example/gpio-interrupts).

To connect an external button to the ARTY board you could either:

- solder a wire directly to BTN0, BTN1, BTN2 and use the clint local interrupts as shown in the examples.
- connect to the ARTY PMOD A or to the Arduino shield and use the plic interrupts as shown in the example.
- modify the [X300 FPGA design](https://github.com/hex-five/multizone-fpga) and reassign gpio lines and interrupt as you like.
